services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: start-dev
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

networks:
  default:
    name: app-dev
    driver: bridge
